### ISSUE TITLE
Aplicar layout para 5 de maio

### ISSUE THREAD

**Issue by ramiroluz** [CMCuritiba/portal-volto#23]

**Comment by ramiroluz** [comment]
Erro de versão do npm:

```
(extranet-cmc) ramiro@silver-dragon:~/workspace/cmcuritiba/extranet.cmcuritiba.pr.leg.br/frontend$ make start
+ yarn start
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at /home/ramiro/workspace/cmcuritiba/extranet.cmcuritiba.pr.leg.br/frontend/.yarn/releases/yarn-3.2.3.cjs:423:2642
    at Object.<anonymous> (/home/ramiro/workspace/cmcuritiba/extranet.cmcuritiba.pr.leg.br/frontend/.yarn/releases/yarn-3.2.3.cjs:738:8846)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
make: *** [Makefile:33: start] Error 1

```

**Comment by ramiroluz** [comment]
Rodar:

`$ nvm use 16`

**Comment by ramiroluz** [comment]
Outra mensagem semelhante e a mesma solução.

```

+ make build-frontend
+ dirname /home/ramiro/workspace/cmcuritiba/gitec.interlegis.leg.br/Makefile
+ make -C ./frontend/ build
+ echo 'Install frontend'
Install frontend
+ yarn install
yarn install v1.22.5
info No lockfile found.
$ if [ -f $(pwd)/mrs.developer.json ]; then if [ -f $(pwd)/node_modules/.bin/missdev ]; then yarn develop; else yarn develop:npx; fi; fi
yarn run v1.22.5
error frontend@1.0.0: The engine "node" is incompatible with this module. Expected version "^14 || ^16". Got "10.24.0"
error Commands cannot run with an incompatible environment.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
make[2]: *** [Makefile:28: install] Error 1
make[1]: *** [Makefile:36: build-frontend] Error 2
make: *** [Makefile:67: build] Error 2
(gitec-py310) ramiro@silver-dragon:~/workspace/cmcuritiba/gitec.interlegis.leg.br$ nvm use 16
Now using node v16.20.0 (npm v8.19.4)
(gitec-py310) ramiro@silver-dragon:~/workspace/cmcuritiba/gitec.interlegis.leg.br$
```

**Comment by ramiroluz** [comment]
Mantendo a issue aberta pois faltam alguns ajustes de css + fonts e falta mudar para react.

**Comment by ramiroluz** [comment]
Encerrando a issue. Adicionei icones usando react. Já dá para customizar o que for necessário e ir melhorando de acordo com as necessidades.

![Captura de tela de 2023-05-17 10-50-36](https://github.com/CMCuritiba/portal-volto/assets/293174/e4487e74-f0e7-475e-abb5-89e8bc63cbab)
